Desafio 3 DSP/Models/ErrorViewModel.cs
namespace Desafio_3_DSP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Desafio 3 DSP/Controllers/ContactoController.cs
using Microsoft.AspNetCore.Mvc;

namespace Desafio_3_DSP.Controllers
{
    public class ContactoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Desafio 3 DSP/Controllers/HomeController.cs
using Desafio_3_DSP.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Desafio_3_DSP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Desafio 3 DSP/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;

namespace Desafio_3_DSP.Controllers
{
    public class MainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Desafio 3 DSP/Views/Contacto/Index.cshtml
@{
    ViewData["Title"] = "Index";    
}

<style>
    .date {
        background: #FFC107;
        width: 65px !important;
        height: 40px !important;
        display: flex;
        align-content: center;
        justify-content: center;
        border-radius: 3px;
    }

    .inline {
        display: flex;
        flex-direction: row;
        align-content: flex-start;
        justify-content: flex-start;
    }

    .type {
        background: #2196F3;
        width: 105px !important;
        height: 30px !important;
        display: flex;
        align-content: center;
        justify-content: center;
        border-radius: 3px;
        margin-left: 10px;
        margin-right: 10px;
        margin-top: 10px;
    }
    .button-margin-top {
        margin-top: 1.5rem;
    }
</style>

<div class="contenido">

    <div class="mt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Library</li>
            </ol>
        </nav>
    </div>

    <div class="row">
        <div class="col-md-3">
            <button class="btn btn-info w-100 mb-3">Agenda</button>
            <div class="card-item">
                <h1 class="title-card"></h1>
                <div class="row">
                    <div class="inline">
                        <div class="date">
                            <span class="mt-2 fw-bold">21 Oct</span>
                        </div>

                        <div class="type">
                            <span class="fw-bold text-white">Académico</span>
                        </div>                                                
                    </div>
                    <p class="mt-2">Último día para retiro de materias y/o retiro total del ciclo carreras de la Dirección de Educación a Distancia</p>
                </div>
            </div>
            <div class="card-item">
                <h1 class="title-card"></h1>
                <div class="row">
                    <div class="inline">
                        <div class="date">
                            <span class="mt-2 fw-bold">31 Oct</span>
                        </div>

                        <div class="type">
                            <span class="fw-bold text-white">Académico</span>
                        </div>
                    </div>
                    <p class="mt-2">Inicia trámites de ingreso para nuevos aspirantes a carreras de la Dirección de Educación a Distancia para Ciclo 01-2025</p>
                </div>
            </div>
            <div class="card-item">
                <h1 class="title-card"></h1>
                <div class="row">
                    <div class="inline">
                        <div class="date">
                            <span class="mt-2 fw-bold">01 Nov</span>
                        </div>

                        <div class="type">
                            <span class="fw-bold text-white">Académico</span>
                        </div>
                    </div>
                    <p class="mt-2">Día de difuntos (asueto)</p>
                </div>
            </div>

            <button class="btn btn-info w-100 mb-3 button-margin-top">Noticias</button>

        </div>
        <div class="col-md-9">
            Espacio para lo demás
        </div>
    </div>
</div>

Desafio 3 DSP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Desafio 3 DSP/Views/Main/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<style>
    .custom-border {
        border-radius: 10px;
    }
    .main-contenido {
        padding: 15px;
    }

    .seccond-contenido, .third-content {
        margin-top: 1.6rem;
    }
    .info-card-img {
        height: 100px;
        width: 100px;
        margin: 10px
    }

    .center-content {
        display: flex !important;
        align-content: center !important;
        justify-content: center !important;
        flex-direction: column;
    }
    .rear-img {
        width: 90%;
        height: auto;
    }

    .welcome-section {
        margin-top: 1.6rem;
    }
</style>

<div class="contenido">
    <div class="main-contenido">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://images.pexels.com/photos/12064/pexels-photo-12064.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="d-block w-100 img-fluid custom-border" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://images.pexels.com/photos/12063/pexels-photo-12063.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="d-block w-100 img-fluid custom-border" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://images.pexels.com/photos/12069/pexels-photo-12069.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" class="d-block w-100 img-fluid custom-border" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>

    <div class="welcome-section">
        <div class="row">
            <div class="col-md-6">
                <h2>Bienvenido</h2>
                <p>La Universidad Don Bosco es una institución salesiana de educación superior con 39 
                    años de trayectoria. Forma parte de la Red de Instituciones Salesianas de Educación 
                    Superior (IUS) en el mundo.  
                </p>
                <p> Somos referente en El Salvador y Centroamérica por nuestro modelo educativo e
                    innovación curricular para la formación integral de la persona, a través de un enfoque
                    por competencias.
                </p>

                <div class="courses-offered">
                    <h3>Carreras a Ofertar</h3>
                    <ul>
                        <li>Ingeniería en Ciencias de la Computación</li>
                        <li>Licenciatura en Administración de Empresas</li>
                        <li>Técnico en Multimedia</li>
                        <li>Ingeniería Industrial</li>
                        <li>Contaduría Pública</li>
                    </ul>
                </div>
            </div>

            <div class="col-md-6">
                <div class="video-container">
                    <video width="100%" controls>
                        <source src="/video/UDB_Video.mp4" type="video/mp4">
                        Tu navegador no soporta el elemento de video.
                    </video>
                </div>
            </div>
        </div>
    </div>

    <div class="seccond-contenido">
        <div class="row">
            <div class="col-md-8">
                <img src="https://www.udb.edu.sv/udb_files/recursos_banners/web/image/publicitario/P9WHK2U9/454_bannerpublicitaria_link_peq_04411820241017.jpg"
                     class="img-fluid" alt="Alternate Text" />
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="text-center">
                        <img src="https://www.udb.edu.sv/udb_files/recursos_banners/web/image/portada/GMADKS2P/159_bannerportada_peq_03230420210116.jpg"
                             class="rear-img" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="third-content">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-2 center-content">
                        <div class="text-center">
                            <img src="~/img/certificate.png" alt="" class="info-card-img"> <br />
                        </div>
                        <h5 class="fw-bold text-center">Nuevas Carreras</h5>
                    </div>
                    <div class="col-md-2 center-content">
                        <div class="text-center">
                            <img src="~/img/flask.png" alt="" class="img-fluid info-card-img"> <br />
                        </div>                        
                        <h5 class="fw-bold text-center">Proyección Social</h5>
                    </div>
                    <div class="col-md-2 center-content d-flex">
                        <div class="text-center">
                            <img src="~/img/graduation.png" alt="" class="img-fluid info-card-img"> <br />
                        </div>                        
                        <h5 class="fw-bold text-center">Certificados</h5>
                    </div>
                    <div class="col-md-2 center-content d-flex">
                        <div class="text-center">
                            <img src="~/img/library.png" alt="" class="img-fluid info-card-img"> <br />
                        </div>                        
                        <h5 class="fw-bold text-center">Biblioteca Virtual</h5>
                    </div>
                    <div class="col-md-2 center-content d-flex">
                        <div class="text-center">
                            <img src="~/img/canvas.png" alt="" class="img-fluid info-card-img"> <br />
                        </div>                        
                        <h5 class="fw-bold text-center">Arte y Cultura</h5>
                    </div>
                    <div class="col-md-2 center-content d-flex">
                        <div class="text-center">
                            <img src="~/img/atom.png" alt="" class="img-fluid info-card-img"> <br />
                        </div>                        
                        <h5 class="fw-bold text-center">Ciencia</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

Desafio 3 DSP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Desafio_3_DSP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Desafio_3_DSP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-primary navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand fw-bold" href="#">UDB +</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="n avbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="ContactoController" asp-action="Index">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Ingreso de materias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Galeria</a>
                        </li>
                        <li class="nav-item text-white">
                            <a class="nav-link disabled" aria-disabled="true">UDB Virtual</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Desafio_3_DSP - <a asp-area="" asp-controller="Main" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>